<?php


namespace App\Controller;


class WorkController extends AppController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index ()
    {

    }

    public function detail ()
    {
        $detailValue = $this->request->getData('detail');
        # エレメント使い分けのため、値を変える
        $elementValue = '';
        if ($detailValue === '1') {
            $elementValue = '1';
        } elseif ($detailValue === '2') {
            $elementValue = '2';
        } elseif ($detailValue === '3') {
            $elementValue = '3';
        } else {
            # 値が1,2,3以外の場合はメイン画面へリダイレクト
            $this->redirect('/main/index');
        }
        $this->set('elementValue', $elementValue);
    }
}
