<?php


namespace App\Controller;


class WorkController extends AppController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

    }
}
